/**
 * @author : Generator(Generator)
 * @date : 2018-05-23
 * @version : 1.0
 * @desc :  generated by gradle
 */

package com.plgrim.ncp.base.entities.datasource1.lgs;

import lombok.Data;
import lombok.EqualsAndHashCode;

import org.apache.ibatis.type.Alias;

import com.plgrim.ncp.base.abstracts.AbstractEntity;

/**
 * 물류 배송
 */
@Data
@EqualsAndHashCode(callSuper=false)
@Alias("lgsDlv")
public class LgsDlv extends AbstractEntity {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 주문 번호
	 * OD || YYYYMMDD || 7자리 Cycle Sequence	 
	 */
	private String ordNo;


	/**
	 * 배송 수거지 순번	 
	 */
	private java.lang.Integer dlvPcupspTurn;


	/**
	 * 배송 순번	 
	 */
	private java.lang.Integer dlvTurn;


	/**
	 * 클레임 번호
	 * ㅁ. CL || YYYYMMDD || 7자리 Cycle Sequence
	 * ㅁ. 수선 클레임인 경우 AS || YYYYMMDD || 7자리 Cycle Sequence	 
	 */
	private String clmNo;


	/**
	 * 국내 배송비 정책 일련번호	 
	 */
	private java.lang.Long dmstcDlvCstPlcSn;


	/**
	 * 해외 배송 국내 배송비 정책 일련번호	 
	 */
	private java.lang.Long ovseaDlvDmstcDlvCstPlcSn;


	/**
	 * 해외 배송비 정책 일련번호	 
	 */
	private java.lang.Long ovseaDlvCstPlcSn;


	/**
	 * ZONE 순번
	 * 지정된 국가별로 그룹하여 묶은 번호	 
	 */
	private java.lang.Integer zoneTurn;


	/**
	 * 상품 최소 무게	 
	 */
	private java.math.BigDecimal godMinWt;


	/**
	 * 배송 요금 이력 순번	 
	 */
	private java.lang.Integer dlvChrgeHistTurn;


	/**
	 * 배송비 부담 주체 코드
	 * ㅁ. 배송비 부담 주체 : DLV_CST_BND_MBD
	 *    >. 자사 : MCOM
	 *    >. 업체 : COM
	 *    >. 고객 : CSTMR	 
	 */
	private String dlvCstBndMbdCd;


	/**
	 * 배송 수단 코드
	 * ㅁ. 배송 수단 : DLV_MN
	 *    >. 택배 : HDRY
	 *    >. 지정 택배 : APPN_HDRY
	 *    >. 매장픽업 : SHOP_PKUP
	 *    >. DHL : DHL
	 *    >. 해외우편 : OVSEA_POST
	 *    >. 일반우편 : GNRL_POST
	 *    >. 등기우편 : RGIST_POST
	 *    >. 편의점택배 : CVNSTOR_HDRY
	 *    >. 용달배송 : DLV_CAR
	 *    >. EMS : EMS
	 *    >. PX : PX
	 *    >. 퀵배송 : QDLV	 
	 */
	private String dlvMnCd;


	/**
	 * 배송 업체 코드
	 * ㅁ. 배송 업체 : DLV_COM
	 *    >. 매장픽업 : SHOP_PKUP
	 *    >. 자체배송 : ONSLF_DLV
	 *    >. ACI Express : ACIEX
	 *    >. AirBoyExpress : AIRBE
	 *    >. CJ-GLS(HTH통합) : CJGLS
	 *    >. CVSnet : CVSNT
	 *    >. GSM 국제택배 : INLOS
	 *    >. KGB택배 : KGBLS
	 *    >. KT로지스 : KTLOG
	 *    >. WIZWA : WIZWA
	 *    >. 경동택배 : KDEXP
	 *    >. 고려택배 : KLOGI
	 *    >. 나이트맨 : KNHTM
	 *    >. 네덱스 : NEDEX
	 *    >. 다젠 : DAZEN
	 *    >. 대신택배 : DAESN
	 *    >. 대한통운 : DRTDR
	 *    >. 대한통운(미국상사) : KGLOP
	 *    >. 동부익스프레스 : DNGBU
	 *    >. 동원로엑스 : LOEXE
	 *    >. 로젠택배 : LOGEN
	 *    >. 사가와 익스프레스 : SCLOG
	 *    >. 스피디익스프레스 : JUSOU
	 *    >. 한진드림익스프레스 : SEDEX
	 *    >. 옐로우캡 : YELLW
	 *    >. 우체국EMS : POSTOFC_EMS
	 *    >. 우체국등기 : POSTOFC_RGIST
	 *    >. 우체국택배 : POSTOFC_HDRY
	 *    >. 이노지스택배 : INNOG
	 *    >. 이젠택배 : EZENS
	 *    >. 일양로지스택배 : ILYNG
	 *    >. 천일택배 : C1001
	 *    >. 트라넷 : TRANT
	 *    >. 하나로택배 : HANAR
	 *    >. 한진택배 : HANJN
	 *    >. 현대택배 : HYDEX
	 *    >. 훼미리택배 : FAMIL
	 *    >. 건영택배 : KNYN
	 *    >. ㈜범한판토스 : PANTOS
	 *    >. 직접입력 : DIRT_INPUT
	 *    >. GOP 당일택배 : GOP
	 *    >. 롯데택배 : LOTTE
	 *    >. CJ대한통운 : CJKEX
	 *    >. SF Express : SFEXP
	 *    >. Gogovan : GOGOVAN	 
	 */
	private String dlvComCd;


	/**
	 * 배송 업체 명
	 * ㅁ. 해외 반품시 배송 업체 코드가 직접입력(DIRT_INPUT) 일때 사용	 
	 */
	private String dlvComNm;


	/**
	 * 집하 상태 코드
	 * ㅁ. 집하 상태 : GDGP_STAT
	 *    >. 예약취소 : RESVE_CNCL
	 *    >. 운송장등록 : WAYBIL_REG
	 *    >. 집하완료 : GDGP_COMPT
	 *    >. 배송완료 : DLV_COMPT
	 *    >. 미집하 : BF_GDGP
	 *    >. 배송불가 : DLV_IMPS	 
	 */
	private String gdgpStatCd;


	/**
	 * 국내 운송장 번호
	 * ㅁ. SQ_WAYBIL_NO 를 이용하여 채번
	 *    >. 50301200000 부터 시작
	 * 
	 * ㅁ. ASIS SEQ_DELI_CPMWBLNUM
	 *    >. Min Value : 50300841000
	 *    >. Max Value : 50301840999
	 *    >. Next Value : 50301095870 (2015-08-17)
	 * 
	 * ㅁ. 추가로 할당받은 SQ_WAYBIL_NO
	 *    >. Min Value : 50365965500
	 *    >. Max Value : 50366065499
	 *    >. Next Value : 50365966548 (2016-02-23)	 
	 */
	private String dmstcWaybilNo;


	/**
	 * 국내 운송장 번호 등록 일시	 
	 */
	private java.util.Date dmstcWaybilNoRegDt;


	/**
	 * HBL 번호	 
	 */
	private String hblNo;


	/**
	 * HBL 번호 등록 일시	 
	 */
	private java.util.Date hblNoRegDt;


	/**
	 * 해외 운송장 번호	 
	 */
	private String ovseaWaybilNo;


	/**
	 * 해외 운송장 번호 등록 일시	 
	 */
	private java.util.Date ovseaWaybilNoRegDt;


	/**
	 * 편의점 택배 승인 번호	 
	 */
	private String cvnstorHdryAprvNo;


	/**
	 * 통화 코드
	 * ISO 4217을 준수
	 * 사용 코드 : CRNCY    통화
	 * KRW    대한민국 원
	 * USD    미국 달러
	 * CNY     런민비 (위안)
	 * JPY    일본 엔	 
	 */
	private String crncyCd;


	/**
	 * 환율 적용 시작 일시	 
	 */
	private java.util.Date exchgRtAplBegDt;


	/**
	 * 기준 통화 금액
	 * 사이트의 기준 통화의 기준이 되는 금액	 
	 */
	private java.math.BigDecimal stdrCrncyAmt;


	/**
	 * 결제 환율 통화 금액
	 * 사이트의 기준 통화를 기준으로 기준 통화금액에 환율을 적용한 금액	 
	 */
	private java.math.BigDecimal payExchgRtCrncyAmt;


	/**
	 * 실제 배송비	 
	 */
	private java.math.BigDecimal realityDlvCst;


	/**
	 * 정책 배송비	 
	 */
	private java.math.BigDecimal plcDlvCst;


	/**
	 * 취소 배송비	 
	 */
	private java.math.BigDecimal cnclDlvCst;


	/**
	 * 반품 배송비	 
	 */
	private java.math.BigDecimal rtgodDlvCst;


	/**
	 * 교환 배송비	 
	 */
	private java.math.BigDecimal exchgDlvCst;


	/**
	 * 배송비 쿠폰 할인 금액	 
	 */
	private java.math.BigDecimal dlvCstCpnDcAmt;


	/**
	 * 배송비 쿠폰 번호
	 * ㅁ. CP || YYYYMMDD || 7자리 Cycle Sequence	 
	 */
	private String dlvCstCpnNo;


	/**
	 * 배송비 쿠폰 프로모션 번호
	 * ㅁ. PR || YYYYMMDD || 7자리 Cycle Sequence
	 * 
	 * ㅁ. 무료/반품/교환 배송비 쿠폰이 즉시할인으로 발급되는 케이스가 있어 해당 컬럼을 추가함	 
	 */
	private String dlvCstCpnPrmNo;


	/**
	 * 출고 운송장 번호 ERP 전송 코드	 
	 */
	private String dlivyWaybilNoErpTrnsmisCd;


	/**
	 * 출고 운송장 번호 ERP 전송 오류 내용	 
	 */
	private String dlivyWaybilNoErpTrnsmisEr;


	/**
	 * 출고 운송장 번호 ERP 전송 일시	 
	 */
	private java.util.Date dlivyWaybilNoErpTrnsmisDt;


	/**
	 * 운송장 번호 ERP 전송 코드	 
	 */
	private String waybilNoErpTrnsmisCd;


	/**
	 * 운송장 번호 ERP 전송 오류 내용	 
	 */
	private String waybilNoErpTrnsmisErrCont;


	/**
	 * 운송장 번호 ERP 전송 일시	 
	 */
	private java.util.Date waybilNoErpTrnsmisDt;


	/**
	 * 배송 업체 전송 대상 여부
	 * ㅁ. 매장 배송, 사용자 직접 반품등 배송이  필요 없는 경우 N 
	 * ㅁ. 배송 업체 배송이 필요 한 경우 Y	 
	 */
	private String dlvComTrnsmisTgtYn;


	/**
	 * 배송 업체 전송 여부	 
	 */
	private String dlvComTrnsmisYn;


	/**
	 * 배송 업체 전송 일시	 
	 */
	private java.util.Date dlvComTrnsmisDt;


	/**
	 * 배송 업체 배송 완료 일시
	 * 실제 배송 업체에서 배송 완료된 일시를 관리하기 위함	 
	 */
	private java.util.Date dlvComDlvComptDt;


	/**
	 * 매장 픽업 SMS 발송 여부
	 * ㅁ. 매장 픽업 주문시 픽업 매장에 상품이 준비되어 SMS를 발송했는지 여부	 
	 */
	private String shopPkupSmsSndYn;


	/**
	 * 메일 발송 여부	 
	 */
	private String mailSndYn;


	/**
	 * 정산 일시	 
	 */
	private java.util.Date calDt;


	/**
	 * 대한통운 미집하 사유 코드
	 * ㅁ. 미집하 사유 : DRTDR_NONGDGP_RESN
	 *    >. 집화이관 : 49
	 *    >. 업체미출고 : 02
	 *    >. 기집화 : 03
	 *    >. 재고부족 : 01
	 *    >. 타택배 : 06
	 *    >. 천재지변 : 07
	 *    >. 주문취소(일반건) : 08
	 *    >. 집배구역불일치 : 09
	 *    >. 집화예정 : 11
	 *    >. 토요휴무 : 12
	 *    >. 취급불가/규격외품 : 13
	 *    >. 반품취소/거부 : 14
	 *    >. 고객사용중 : 16
	 *    >. 지정일회수 : 17
	 *    >. 고객부재 : 18
	 *    >. 고객정보오류 : 21
	 *    >. 교환물건미도착 : 22
	 *    >. 회수건없음(업체오류) : 23
	 *    >. 통화안됨(4일이상) : 25
	 *    >. 합포장(미사용) : 26
	 *    >. 시간부족 : 33
	 *    >. 차량고장 : 34
	 *    >. 포장미비 : 35
	 *    >. 도서/외곽지역 : 38
	 *    >. 중복예약 : 44
	 *    >. 기타2 : 48
	 *    >. 보내는분 요청 : 50
	 *    >. 받는분 요청 : 51	 
	 */
	private String drtdrNongdgpResnCd;


	/**
	 * 대한통운 미배달 사유 코드
	 * ㅁ. 미배달 사유 : DRTDR_NONDLVR_RESN
	 *    >. 고객정보오류 : 01
	 *    >. 고객부재 : 02
	 *    >. 지연도착 : 05
	 *    >. 분류오류 : 06
	 *    >. 통화불가능 : 08
	 *    >. 수취거부 : 09
	 *    >. 천재지변 : 11
	 *    >. 착지변경 : 16
	 *    >. 상품사고(파손/분실) : 21
	 *    >. 토요휴무 : 23
	 *    >. 지정일배달 : 24
	 *    >. 차량고장/사고 : 32
	 *    >. 도서/외곽지역 : 33
	 *    >. 특판잔류 : 42
	 *    >. 결재불가 : 55
	 *    >. 배달전취소 : 56	 
	 */
	private String drtdrNondlvrResnCd;


	/**
	 * 등록자 ID
	 * 등록한 관리자 번호	 
	 */
	private String regtrId;


	/**
	 * 등록 일시	 
	 */
	private java.util.Date regDt;


	/**
	 * 수정자 ID
	 * 수정한 관리자 번호	 
	 */
	private String udterId;


	/**
	 * 수정 일시	 
	 */
	private java.util.Date udtDt;


	/**
	 * 주문 확인 여부
	 * ㅁ.배송 매장 배정 주문의 경우 배정된 배송 매장에서 해당 주문은 확인 하였는가 여부	 
	 */
	private String ordCnfirmYn;
	
	
	private String dlvShopDlvYn;

	
}
