/**
 * @author : Generator(Generator)
 * @date : 2018-05-23
 * @version : 1.0
 * @desc :  generated by gradle
 */

package com.plgrim.ncp.base.entities.datasource1.sys;

import lombok.Data;
import lombok.EqualsAndHashCode;

import org.apache.ibatis.type.Alias;

import com.plgrim.ncp.base.abstracts.AbstractEntity;

/**
 * 시스템 몰
 */
@Data
@EqualsAndHashCode(callSuper=false)
@Alias("sysMall")
public class SysMall extends AbstractEntity {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 몰 ID	 
	 */
	private String mallId;


	/**
	 * SSO 그룹 코드
	 * ㅁ. SSO 그룹 : SSO_GRP
	 *    >.  FNF 그룹 : FNF_GRP	 
	 */
	private String ssoGrpCd;


	/**
	 * 사용 여부	 
	 */
	private String useYn;


	/**
	 * 정산 사용 여부	 
	 */
	private String calUseYn;


	/**
	 * 몰 명	 
	 */
	private String mallNm;


	/**
	 * 몰 URL	 
	 */
	private String mallUrl;


	/**
	 * 법인 명	 
	 */
	private String cprNm;


	/**
	 * 대표자 명	 
	 */
	private String rprstivNm;


	/**
	 * 법인등록번호	 
	 */
	private String cprRegNo;


	/**
	 * 사업자등록번호	 
	 */
	private String bmanRegNo;


	/**
	 * 통신판매신고번호	 
	 */
	private String mosRegno;


	/**
	 * 대표 이메일	 
	 */
	private String rprstEmail;


	/**
	 * 개인정보 관리 책임자 명	 
	 */
	private String psnlInfoManageMgrNm;


	/**
	 * 정렬 순서	 
	 */
	private java.lang.Integer sortSeq;


	/**
	 * 알림톡 사용 여부
	 * ㅁ. 카카오톡에서 제공하는 알림톡을 사용하는 지에 대한 여부
	 * 
	 * ㅁ. 알림톡을 사용하는 경우 회원은 설정에 따라 발송하며 비회원은 알림톡 우선으로 발송
	 * 
	 * ㅁ. 알림톡을 사용하지 않는 경우 회원 설정에 상관 없이 문자를 이용하여 발송	 
	 */
	private String ntcnTakUseYn;


	/**
	 * 우편번호	 
	 */
	private String postNo;


	/**
	 * 기본주소	 
	 */
	private String baseAddr;


	/**
	 * 상세주소	 
	 */
	private String detailAddr;


	/**
	 * 전화 국가번호	 
	 */
	private String telNationNo;


	/**
	 * 전화 지역번호	 
	 */
	private String telAreaNo;


	/**
	 * 전화 국번호	 
	 */
	private String telTlofNo;


	/**
	 * 전화 국내번호	 
	 */
	private String telTlofWthnNo;


	/**
	 * 팩스 국가번호	 
	 */
	private String faxNationNo;


	/**
	 * 팩스 지역번호	 
	 */
	private String faxAreaNo;


	/**
	 * 팩스 국번호	 
	 */
	private String faxTlofNo;


	/**
	 * 팩스 국내번호	 
	 */
	private String faxTlofWthnNo;


	/**
	 * 고객센터 이메일	 
	 */
	private String ccEmail;


	/**
	 * 고객센터 전화 국가번호	 
	 */
	private String ccTelNationNo;


	/**
	 * 고객센터 전화 지역번호	 
	 */
	private String ccTelAreaNo;


	/**
	 * 고객센터 전화 국번호	 
	 */
	private String ccTelTlofNo;


	/**
	 * 고객센터 전화 국내번호	 
	 */
	private String ccTelTlofWthnNo;


	/**
	 * 고객센터 팩스 국가번호	 
	 */
	private String ccFaxNationNo;


	/**
	 * 고객센터 팩스 지역번호	 
	 */
	private String ccFaxAreaNo;


	/**
	 * 고객센터 팩스 국번호	 
	 */
	private String ccFaxTlofNo;


	/**
	 * 고객센터 팩스 국내번호	 
	 */
	private String ccFaxTlofWthnNo;


	/**
	 * 등록자 ID
	 * 등록한 관리자 번호	 
	 */
	private String regtrId;


	/**
	 * 등록 일시	 
	 */
	private java.util.Date regDt;


	/**
	 * 수정자 ID
	 * 수정한 관리자 번호	 
	 */
	private String udterId;


	/**
	 * 수정 일시	 
	 */
	private java.util.Date udtDt;

	
}
