/**
 * @author : Generator(Generator)
 * @date : 2018-05-23
 * @version : 1.0
 * @desc :  generated by gradle
 */

package com.plgrim.ncp.base.entities.datasource1.sys;

import lombok.Data;
import lombok.EqualsAndHashCode;

import org.apache.ibatis.type.Alias;

import com.plgrim.ncp.base.abstracts.AbstractEntity;

/**
 * 시스템 품목 무게
 */
@Data
@EqualsAndHashCode(callSuper=false)
@Alias("sysPrdlstWt")
public class SysPrdlstWt extends AbstractEntity {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 품목 코드
	 * ㅁ. ERP와 연동하여 처리 된건은 2자리	 
	 */
	private String prdlstCd;


	/**
	 * 시즌 그룹 코드
	 * ㅁ. 시즌 그룹 : SESON_GRP
	 *    >. SS : SS
	 *    >. FW : FW	 
	 */
	private String sesonGrpCd;


	/**
	 * 사용 여부	 
	 */
	private String useYn;


	/**
	 * 상품 무게
	 * ㅁ. ㎏ 단위	 
	 */
	private java.math.BigDecimal godWt;


	/**
	 * 등록자 ID
	 * 등록한 관리자 번호	 
	 */
	private String regtrId;


	/**
	 * 등록 일시	 
	 */
	private java.util.Date regDt;


	/**
	 * 수정자 ID
	 * 수정한 관리자 번호	 
	 */
	private String udterId;


	/**
	 * 수정 일시	 
	 */
	private java.util.Date udtDt;

	
}
