/**
 * @author : Generator(Generator)
 * @date : 2018-05-23
 * @version : 1.0
 * @desc :  generated by gradle
 */

package com.plgrim.ncp.base.entities.datasource1.dsp;

import lombok.Data;
import lombok.EqualsAndHashCode;

import org.apache.ibatis.type.Alias;

import com.plgrim.ncp.base.abstracts.AbstractEntity;

/**
 * 전시 기획전
 */
@Data
@EqualsAndHashCode(callSuper=false)
@Alias("dspPromt")
public class DspPromt extends AbstractEntity {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 기획전 일련번호
	 * "1"부터 오라클 시퀀스(MPD_SPDP_BASE_SQ01)를 사용해서 발행	 
	 */
	private java.lang.Long promtSn;


	/**
	 * 기획전 그룹 일련번호
	 */
	private java.lang.Long promtGrpSn;


	/**
	 * 기획전 명
	 * ㅁ. 카테고리에 적용된 언어에 따라서 카테고리명, 이미지를 적용하도록 함.	 
	 */
	private String promtNm;


	/**
	 * 기획전 설명	 
	 */
	private String promtDscr;


	/**
	 * 기획전 승인 상태 코드
	 * ㅁ. 기획전 상태 : PROMT_STAT
	 *    >. 승인대기 : APRV_WAIT
	 *    >. 승인완료 : APRV_COMPT
	 *    >. 승인거부 : APRV_REJECT	 
	 */
	private String promtAprvStatCd;


	/**
	 * 기획전 승인 일시	 
	 */
	private java.util.Date promtAprvDt;


	/**
	 * 기획전 승인 거부 일시	 
	 */
	private java.util.Date promtAprvRejectDt;


	/**
	 * 기획전 승인 거부 사유 내용	 
	 */
	private String promtAprvRejectResnCont;


	/**
	 * 기획전 유형 코드
	 * ㅁ. 기획전 유형 : PROMT_TP
	 *    >. 일반기획전 : GNRL_PROMT
	 *    >. 딜 기획전 : DIL_PROMT	 
	 */
	private String promtTpCd;


	/**
	 * 기획전 구분자 유형 코드
	 * ㅁ. 기획전 구분자 유형 : PROMT_SPRPR_TP
	 *    >. 텍스트 : TEXT
	 *    >. 이미지 : IMG	 
	 */
	private String promtSprtrTpCd;


	/**
	 * 담당 MD 관리자 ID	 
	 */
	private String chrgMdAdminId;


	/**
	 * 전시 시작 일시
	 * 전시시작일시(YYYYMMDDHH24MISS)	 
	 */
	private java.util.Date dspBegDt;


	/**
	 * 전시 종료 일시
	 * 전시종료일시(YYYYMMDDHH24MISS)	 
	 */
	private java.util.Date dspEndDt;


	/**
	 * 전시 여부
	 * 전시여부	 
	 */
	private String dspYn;


	/**
	 * 전시 기간 노출 여부	 
	 */
	private String dspPdExpsrYn;


	/**
	 * GNB 상단 배너 노출 여부	 
	 */
	private String gnbUpendBannerExpsrYn;


	/**
	 * 정렬 순서
	 * 우선 순위	 
	 */
	private java.lang.Integer sortSeq;


	/**
	 * 특정 URL 전시 여부
	 * ㅁ. 특정 URL 전시 
	 *    >. Y인 경우 일반 카테고리에서는 전시 되지 않음
	 *    >. 특정 URL을 통해 들어 올 때만 전시
	 *    >. 전시 여부에 종속적	 
	 */
	private String spcifyUrlDspYn;


	/**
	 * 기획전 노출 구분 코드
	 * ㅁ. 기획전 노출 구분 : PROMT_EXPSR_SECT
	 *    >. Special : ESPECIAL
	 *    >. Men : EMEN
	 *    >. Women : EWOMEN
	 *    >. Kids : EKIDS
	 *    >. Outdoor : EOUTDOOR
	 *    >. Acc : EACC
	 *    >. Outlet : EOUTLET	 
	 */
	private String promtExpsrSectCd;


	/**
	 * 전시 상품 정렬 기준 코드
	 * ㅁ. 전시 상품 정렬 순서 : DSP_GOD_SORT_STDR
	 *    >. 신상품순 : NEW_GOD_SEQ(PROMO)
	 *    >. 판매수량순 : SALE_QTY_SEQ
	 *    >. 높은할인율순 : BEST_DC_SEQ
	 *    >. 높은가격순 : BEST_PRC_SEQ
	 *    >. 낮은가격순 : LWET_PRC_SEQ(PROMO)
	 *    >. 구매후기순 : PCH_PS_SEQ
	 *    >. MD추천순 : MD_RECOMMEND_SEQ
	 *    >. 사용 안함 : USE_NOT
	 * 
	 * ㅁ. 보조코드(PROMO)를 사용하여 낮은가격순과 신상품순만 사용	 
	 */
	private String dspGodSortStdrCd;


	/**
	 * PC 목록 노출 건수 코드
	 * ㅁ. 목록 노출 건수 : PC_LIST_EXPSR_CNT
	 *    >. 3단 : 3PCE
	 *    >. 4단 : 4PCE	 
	 */
	private String pcListExpsrCntCd;


	/**
	 * 모바일 목록 노출 건수 코드
	 * ㅁ. 목록 노출 건수 : MOBILE_LIST_EXPSR_CNT
	 *    >. 2단 : 2PCE
	 *    >. 3단 : 3PCE	 
	 */
	private String mobileListExpsrCntCd;


	/**
	 * 상품평 노출 구분 코드
	 * ㅁ. 상품평 노출 구분 : GOD_EVL_EXPSR_SECT
	 *    >. 리뷰 등록 최신 순 : GOD_EVL_REG_SEQ
	 *    >. 평점 순 : SCR_SEQ	 
	 */
	private String godEvlExpsrSectCd;


	/**
	 * 이미지 상품평 우선 노출 여부
	 * 포토상품평으로 구분되는 상품평을 우선정렬해서 노출시텨주기 위한 컬럼	 
	 */
	private String imgGodEvlPrioExpsrYn;


	/**
	 * PC 상품평 목록 수량	 
	 */
	private java.lang.Long pcGodEvlListQty;


	/**
	 * 모바일 상품평 목록 수량	 
	 */
	private java.lang.Long mobileGodEvlListQty;


	/**
	 * 등록자 ID
	 * 등록한 관리자 번호	 
	 */
	private String regtrId;


	/**
	 * 등록 일시	 
	 */
	private java.util.Date regDt;


	/**
	 * 수정자 ID
	 * 수정한 관리자 번호	 
	 */
	private String udterId;


	/**
	 * 수정 일시	 
	 */
	private java.util.Date udtDt;

	
}
