/**
 * @author : Generator(Generator)
 * @date : 2018-05-23
 * @version : 1.0
 * @desc :  generated by gradle
 */

package com.plgrim.ncp.base.entities.datasource1.lgs;

import lombok.Data;
import lombok.EqualsAndHashCode;

import org.apache.ibatis.type.Alias;

import com.plgrim.ncp.base.abstracts.AbstractEntity;

/**
 * 물류 배송 회수지시 이력
 */
@Data
@EqualsAndHashCode(callSuper=false)
@Alias("lgsDlvRtrvlDrctHist")
public class LgsDlvRtrvlDrctHist extends AbstractEntity {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 클레임 번호
	 * ㅁ. CL || YYYYMMDD || 7자리 Cycle Sequence
	 * ㅁ. 수선 클레임인 경우 AS || YYYYMMDD || 7자리 Cycle Sequence	 
	 */
	private String clmNo;


	/**
	 * 배송 수거지 순번	 
	 */
	private java.lang.Integer dlvPcupspTurn;


	/**
	 * 배송 순번	 
	 */
	private java.lang.Integer dlvTurn;


	/**
	 * 회수지시 순번	 
	 */
	private java.lang.Integer rtrvlDrctTurn;


	/**
	 * 주문 번호
	 * OD || YYYYMMDD || 7자리 Cycle Sequence	 
	 */
	private String ordNo;


	/**
	 * 회수지시 일시	 
	 */
	private java.util.Date rtrvlDrctDt;


	/**
	 * 배송 업체 코드
	 * ㅁ. 배송 업체 : DLV_COM
	 *    >. 매장픽업 : SHOP_PKUP
	 *    >. 자체배송 : ONSLF_DLV
	 *    >. ACI Express : ACIEX
	 *    >. AirBoyExpress : AIRBE
	 *    >. CJ-GLS(HTH통합) : CJGLS
	 *    >. CVSnet : CVSNT
	 *    >. GSM 국제택배 : INLOS
	 *    >. KGB택배 : KGBLS
	 *    >. KT로지스 : KTLOG
	 *    >. WIZWA : WIZWA
	 *    >. 경동택배 : KDEXP
	 *    >. 고려택배 : KLOGI
	 *    >. 나이트맨 : KNHTM
	 *    >. 네덱스 : NEDEX
	 *    >. 다젠 : DAZEN
	 *    >. 대신택배 : DAESN
	 *    >. 대한통운 : DRTDR
	 *    >. 대한통운(미국상사) : KGLOP
	 *    >. 동부익스프레스 : DNGBU
	 *    >. 동원로엑스 : LOEXE
	 *    >. 로젠택배 : LOGEN
	 *    >. 사가와 익스프레스 : SCLOG
	 *    >. 스피디익스프레스 : JUSOU
	 *    >. 한진드림익스프레스 : SEDEX
	 *    >. 옐로우캡 : YELLW
	 *    >. 우체국EMS : POSTOFC_EMS
	 *    >. 우체국등기 : POSTOFC_RGIST
	 *    >. 우체국택배 : POSTOFC_HDRY
	 *    >. 이노지스택배 : INNOG
	 *    >. 이젠택배 : EZENS
	 *    >. 일양로지스택배 : ILYNG
	 *    >. 천일택배 : C1001
	 *    >. 트라넷 : TRANT
	 *    >. 하나로택배 : HANAR
	 *    >. 한진택배 : HANJN
	 *    >. 현대택배 : HYDEX
	 *    >. 훼미리택배 : FAMIL
	 *    >. 건영택배 : KNYN
	 *    >. ㈜범한판토스 : PANTOS
	 *    >. 직접입력 : DIRT_INPUT	 
	 */
	private String dlvComCd;


	/**
	 * 국내 운송장 번호	 
	 */
	private String dmstcWaybilNo;


	/**
	 * 등록자 ID
	 * 등록한 관리자ID나 회원 번호	 
	 */
	private String regtrId;


	/**
	 * 등록 일시	 
	 */
	private java.util.Date regDt;


	/**
	 * 수정자 ID
	 * 수정한 관리자ID나 회원 번호	 
	 */
	private String udterId;


	/**
	 * 수정 일시	 
	 */
	private java.util.Date udtDt;

	
}
