/**
 * @author : Generator(Generator)
 * @date : 2018-05-23
 * @version : 1.0
 * @desc :  generated by gradle
 */

package com.plgrim.ncp.base.entities.datasource1.sys;

import lombok.Data;
import lombok.EqualsAndHashCode;

import org.apache.ibatis.type.Alias;

import com.plgrim.ncp.base.abstracts.AbstractEntity;

/**
 * 시스템 관리자 사용 로그
 */
@Data
@EqualsAndHashCode(callSuper=false)
@Alias("sysAdminUseLog")
public class SysAdminUseLog extends AbstractEntity {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 관리자 ID	 
	 */
	private String adminId;


	/**
	 * 메뉴 일련번호	 
	 */
	private java.lang.Long menuSn;


	/**
	 * 접속 일시	 
	 */
	private java.util.Date conectDt;


	/**
	 * 접속 IP	 
	 */
	private String conectIp;

	
}
