/**
 * @author : Generator(Generator)
 * @date : 2018-05-23
 * @version : 1.0
 * @desc :  generated by gradle
 */

package com.plgrim.ncp.base.entities.datasource1.com;

import lombok.Data;
import lombok.EqualsAndHashCode;

import org.apache.ibatis.type.Alias;

import com.plgrim.ncp.base.abstracts.AbstractEntity;

/**
 * 업체 해외 배송 ZONE 국가
 */
@Data
@EqualsAndHashCode(callSuper=false)
@Alias("comOvseaDlvZoneNation")
public class ComOvseaDlvZoneNation extends AbstractEntity {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 해외 배송비 정책 일련번호	 
	 */
	private java.lang.Long ovseaDlvCstPlcSn;


	/**
	 * ZONE 순번
	 * 지정된 국가별로 그룹하여 묶은 번호	 
	 */
	private java.lang.Integer zoneTurn;


	/**
	 * 배송 국가 코드
	 * ㅁ. ISO 3166-1에서 규정하는 두 자리 국가 코드를 적용 함
	 *   >. 대한민국:KR 외 243개 국가에 대한 코드를 정의 함
	 * 
	 * ㅁ. 국가 : NATION
	 *    >. 대한민국 : kr
	 *    >. 미국 : us
	 *    >. 중화인민공화국 : cn
	 *    >. 등등....	 
	 */
	private String dlvNationCd;


	/**
	 * 해외 배송 수단 구분 코드
	 * ㅁ. 중국 배송시 범한판토스의 PX 인지 EMS 배송인지 구분하는 코드이며 PX의 경우 배송비에 행우세를 포함하여 배송비를 계산하고 EMS의 경우 행우세는 포함하지 않는다. 
	 *  다른 나라의 경우 PX와 EMS 중 하나만을 사용한다.	 
	 */
	private String ovseaDlvMnSectCd;


	/**
	 * 대륙 구분 코드
	 * ㅁ. 대륙 구분 : CNTINT_SECT
	 *    >. 북아메리카 : NORTH_AMERICA
	 *    >. 중앙아메리카 : CENTRAL_AMERICA
	 *    >.남아메리카 : SOUTH_AMERICA
	 *    >.중동 : MIDDLE_EAST
	 *    >.유럽 : EUROPE
	 *    >.아시아 : ASIA
	 *    >.아프리카 : AFRICA
	 *    >.오세아니아 : OCEANIA	 
	 */
	private String cntintSectCd;


	/**
	 * 배송 가능 국가 여부	 
	 */
	private String dlvPsbNationYn;


	/**
	 * 등록자 ID
	 * 등록한 관리자 번호	 
	 */
	private String regtrId;


	/**
	 * 등록 일시	 
	 */
	private java.util.Date regDt;


	/**
	 * 수정자 ID
	 * 수정한 관리자 번호	 
	 */
	private String udterId;


	/**
	 * 수정 일시	 
	 */
	private java.util.Date udtDt;

	
}
