/**
 * @author : Generator(Generator)
 * @date : 2018-05-23
 * @version : 1.0
 * @desc :  generated by gradle
 */

package com.plgrim.ncp.base.entities.datasource1.god;

import lombok.Data;
import lombok.EqualsAndHashCode;

import org.apache.ibatis.type.Alias;

import com.plgrim.ncp.base.abstracts.AbstractEntity;

/**
 * 상품 공지 브랜드 연결
 */
@Data
@EqualsAndHashCode(callSuper=false)
@Alias("godNotiBrndCnnc")
public class GodNotiBrndCnnc extends AbstractEntity {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 상품 공지 일련번호	 
	 */
	private java.lang.Long godNotiSn;


	/**
	 * 브랜드 ID
	 * ㅁ. 온라인에서 사용하는 브랜드 ID	 
	 */
	private String brndId;


	/**
	 * 시즌 그룹 코드
	 * ㅁ. 시즌 그룹 : SESON_GRP
	 *    >. SS : SS
	 *    >. FW : FW	 
	 */
	private String sesonGrpCd;


	/**
	 * 시즌 코드
	 * ㅁ. ERP에서 연계 받는 코드	 
	 */
	private String sesonCd;


	/**
	 * 삭제 여부	 
	 */
	private String deleteYn;


	/**
	 * 등록자 ID
	 * 등록한 관리자 번호	 
	 */
	private String regtrId;


	/**
	 * 등록 일시	 
	 */
	private java.util.Date regDt;


	/**
	 * 수정자 ID
	 * 수정한 관리자 번호	 
	 */
	private String udterId;


	/**
	 * 수정 일시	 
	 */
	private java.util.Date udtDt;

	
}
