/**
 * @author : Generator(Generator)
 * @date : 2018-05-23
 * @version : 1.0
 * @desc :  generated by gradle
 */

package com.plgrim.ncp.base.entities.datasource1.mbr;

import lombok.Data;
import lombok.EqualsAndHashCode;

import org.apache.ibatis.type.Alias;

import com.plgrim.ncp.base.abstracts.AbstractEntity;

/**
 * 회원 혜택 지급 이력
 */
@Data
@EqualsAndHashCode(callSuper=false)
@Alias("mbrBnefPymntHist")
public class MbrBnefPymntHist extends AbstractEntity {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 회원 번호
	 * ㅁ. 회원 가입시 부여되는 고유한 관리 번호
	 *    >. MB || YYYYMMDD || 7자리 Cycle	 
	 */
	private String mbrNo;


	/**
	 * 혜택 지급 순번	 
	 */
	private java.lang.Integer bnefPymntTurn;


	/**
	 * 혜택 일련번호	 
	 */
	private java.lang.Long bnefSn;


	/**
	 * 혜택 상세 순번	 
	 */
	private java.lang.Integer bnefDetailTurn;


	/**
	 * 몰 ID	 
	 */
	private String mallId;


	/**
	 * 언어 코드
	 * ㅁ. 코드 테이블 규칙에 따라 대문자를 사용한 ISO 639 표준에 따른다
	 * 
	 * ㅁ. 언어 : LANG
	 *    >. 한국어 : KOR
	 *    >. 중국어 : CHI
	 *    >. 영어 : ENG
	 *    >. 일본어 : JPN	 
	 */
	private String langCd;


	/**
	 * 디바이스 코드
	 * ㅁ. 디바이스를 정의
	 * 
	 * ㅁ. 디바이스 : DVC
	 *    >. PC : PC
	 *    >. 모바일 웹 : MOBILE_WEB
	 *    >. 모바일 앱 : MOBILE_APP	 
	 */
	private String dvcCd;


	/**
	 * 모바일 어플리케이션 구분 코드
	 * ㅁ. 모바일 어플리케이션 구분 : MOBILE_APP_SECT
	 *    >. 디스커버리 앱 : dx_app	 
	 */
	private String mobileAppSectCd;


	/**
	 * 혜택 지급 유형 코드
	 * ㅁ. BNEF_PYMNT_TP : 혜택 지급 유형
	 *    >. MBSH_PNT : 멤버쉽 포인트
	 *    >. WEB_PNT : 퍼플코인
	 *    >. CPN : 쿠폰	 
	 */
	private String bnefPymntTpCd;


	/**
	 * 포인트 지급 금액
	 * 멤버쉽포인트, 웹포인트(퍼플코인) 에 대한  지급 금액을 입력	 
	 */
	private java.math.BigDecimal pntPymntAmt;


	/**
	 * 프로모션 번호
	 * ㅁ. PR || YYYYMMDD || 7자리 Cycle Sequence
	 * 
	 * 쿠폰에 대한 프로모션 번호 입력	 
	 */
	private String prmNo;


	/**
	 * 추천인 회원 번호
	 * ㅁ. 회원 가입시 부여되는 고유한 관리 번호
	 *    >. MB || YYYYMMDD || 7자리 Cycle	 
	 */
	private String recomendrMbrNo;


	/**
	 * 피추천인 회원 번호
	 * ㅁ. 회원 가입시 부여되는 고유한 관리 번호
	 *    >. MB || YYYYMMDD || 7자리 Cycle	 
	 */
	private String recomendeMbrNo;


	/**
	 * 지급 일시
	 * ㅁ. 기존에 지급 받은 경우 지급일이 가입일보다 이전 일 수있음.	 
	 */
	private java.util.Date pymntDt;


	/**
	 * 이전 지급 회원 번호
	 * ㅁ. 탈퇴후 6개월이내에 재가입 할 경우 회원 탈퇴 인증 테이블의 CI / DI 값과 비교하여 해당 회원이 동일 혜택을 받은 이력이 있으면 해당 회원의 회원 번호를 입력	 
	 */
	private String bfPymntMbrNo;


	/**
	 * 대상 회원 유형 코드
	 * ㅁ. 대상 회원 유형 : TGT_MBR_TP
	 *    >. 비회원 : NMBR
	 *    >. 온라인 회원 : ONLINE_MBR
	 *    >. 멤버쉽 회원 : UNITY_MBR	 
	 */
	private String tgtMbrTpCd;


	/**
	 * 대상 회원 속성 코드
	 * ㅁ. 대상 회원 속성 : TGT_MBR_ATRB
	 *    >. 일반 회원 : GNRL_MBR
	 *    >. 임직원 : EMP	 
	 */
	private String tgtMbrAtrbCd;


	/**
	 * 혜택 지급 성공 여부	 
	 */
	private String bnefPymntSuccesYn;


	/**
	 * 혜택 지급 실패 사유 내용	 
	 */
	private String bnefPymntFailrResnCont;


	/**
	 * 대상 회원 IP	 
	 */
	private String tgtMbrIp;


	/**
	 * 등록자 ID
	 * 등록한 관리자 번호	 
	 */
	private String regtrId;


	/**
	 * 등록 일시	 
	 */
	private java.util.Date regDt;


	/**
	 * 수정자 ID
	 * 수정한 관리자 번호	 
	 */
	private String udterId;


	/**
	 * 수정 일시	 
	 */
	private java.util.Date udtDt;

	
}
