/**
 * @author : Generator(Generator)
 * @date : 2018-05-23
 * @version : 1.0
 * @desc :  generated by gradle
 */

package com.plgrim.ncp.base.entities.datasource1.god;

import lombok.Data;
import lombok.EqualsAndHashCode;

import org.apache.ibatis.type.Alias;

import com.plgrim.ncp.base.abstracts.AbstractEntity;

/**
 * 상품 단품 재고 이력
 */
@Data
@EqualsAndHashCode(callSuper=false)
@Alias("godItmInvHist")
public class GodItmInvHist extends AbstractEntity {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 이력 일시	 
	 */
	private java.util.Date histDt;


	/**
	 * 재고 유형 코드
	 * ㅁ. 재고 유형 : INV_TP
	 *    >. 주문 : ORD
	 *    >. 취소 : CNCL
	 *    >. 반품 : RTGOD
	 *    >. 교환 : EXCHG
	 *       - 교환 출고 : EXCHG_DLIVY
	 *       - 교환 입고 : EXCHG_WRHS
	 *    >. 관리자 조정 : ADMIN_MDAT
	 *    >. ERP 연계 : ERP_CNTC
	 *    >. 매장 변경 : SHOP_MOD
	 *    >. 재고 조정 : INV_MDAT
	 *    >. 결품 : SHTG
	 *    >. 재출고 : REDLIVY	 
	 */
	private String invTpCd;


	/**
	 * 정상 여부	 
	 */
	private String nrmltYn;


	/**
	 * 상품 번호
	 * ㅁ. 상품 유형 1자리 || 업체 코드 3자리 || YYMMDD || 5자리 Cycle Sequence	 
	 */
	private String godNo;


	/**
	 * 단품 번호
	 * IT || YYYYMMDD || 7자리 Cycle Sequence	 
	 */
	private String itmNo;


	/**
	 * 매장 ID	 
	 */
	private String shopId;


	/**
	 * 주문 번호
	 * OD || YYYYMMDD || 7자리 Cycle Sequence	 
	 */
	private String ordNo;


	/**
	 * 클레임 번호
	 * ㅁ. CL || YYYYMMDD || 7자리 Cycle Sequence
	 * ㅁ. 수선 클레임인 경우 AS || YYYYMMDD || 7자리 Cycle Sequence	 
	 */
	private String clmNo;


	/**
	 * 회원 번호
	 * ㅁ. 회원 가입시 부여되는 고유한 관리 번호
	 *    >. MB || YYYYMMDD || 7자리 Cycle
	 * 
	 * ㅁ. 재고를 변경한 회원 번호	 
	 */
	private String mbrNo;


	/**
	 * 관리자 ID
	 * ㅁ. 재고를 변경한 관리자 ID	 
	 */
	private String adminId;


	/**
	 * 총 가용 재고 증감 수량	 
	 */
	private java.lang.Long totUsefulInvIrdsQty;


	/**
	 * 온라인 한정 재고 증감 수량	 
	 */
	private java.lang.Long onlneLmttInvIrdsQty;


	/**
	 * 제휴 업체 한정 재고 증감 수량	 
	 */
	private java.lang.Long affComLmttInvIrdsQty;


	/**
	 * 예약 재고 증감 수량	 
	 */
	private java.lang.Long resveInvIrdsQty;

	
}
